### ISSUE TITLE
Feature request: support for @sveltejs/adapter-cloudflare-workers

### ISSUE THREAD

**Issue by ryanrussell** [navneetsharmaui/sveltekit-starter#14]
Hello,

Any chance you can add support for https://www.npmjs.com/package/@sveltejs/adapter-cloudflare-workers ?

Thanks in advance

**Comment by navneetsharmaui** [comment]
@ryanrussell sure I will add

**Comment by navneetsharmaui** [comment]
@ryanrussell as there are not many Cloudflare open users. I don't think there is a need to add it. In addition, all the adapters are not stable and are not working properly.
