### ISSUE TITLE
Storybook and Tailwind

### ISSUE THREAD

**Issue by magick93** [navneetsharmaui/sveltekit-starter#17]
Hello

I'm unable to get the Tailwind css to display when viewing in Storybook.

Do you have any suggestions for what might be the problem?

**Comment by obasekietinosa** [comment]
Hello! Did you resolve this? I've run into the same issue with Tailwind styles not being applied on Storybook.

**Comment by magick93** [comment]
I did get it working but I'm not sure how I managed to do it.

Try `npx sb upgrade`

**Comment by magick93** [comment]
Actually I didnt get it filly solved.

storybook is displaying some tailwind css, eg, some bg colors but not others. 

But when I run `yarn run dev` styles are applied as expected

**Comment by navneetsharmaui** [comment]
@magick93 If you have used the starter project that I've created you would not face the tailwindcss issue in the storybook.
I've tested and created components with storybook and tailwind in the starter project.
