### ISSUE TITLE
Removing yarn cache

### ISSUE THREAD

**Issue by Himujjal** [navneetsharmaui/sveltekit-starter#19]
The yarn cache (.yarn folder) is 105MB huge which is a completely big no-no for such projects. 
Considering I and many other use pnpm for most of the workflow, yarn as default might not a good choice. I think keeping the repo package manager independent would be a good choice.

**Comment by navneetsharmaui** [comment]
@Himujjal You are right initially I did that for my personal project and since the other people started using the project it didn't make sense for them to download the large dependencies. I've removed that setup now.
