### ISSUE TITLE
Upgrade to Tailwind 2.1 and simplify config

### ISSUE THREAD

**Issue by babichjacob** [navneetsharmaui/sveltekit-starter#2]
This is just an advisory / notice that you can make things even nicer.

You no longer need `@tailwindcss/jit` since `tailwindcss` 2.1.
You then reduce the Tailwind config to this:
```js
module.exports = {
	mode: "jit",
	purge: [
		"./src/**/*.{html,js,svelte,ts}",
	],
	theme: {
		extend: {},
	},
	plugins: [],
};
```

because the custom purge extractor is not supported in JIT, and because variants don't need to be configured (as far as I know) in JIT either.

**Comment by navneetsharmaui** [comment]
Thanks, @babichjacob  for the feedback I will explore it once about it and update the project.
