### ISSUE TITLE
Storybook crashes when path aliases are used

### ISSUE THREAD

**Issue by ihym** [navneetsharmaui/sveltekit-starter#21]
If I try
```
import { Button } from '$ui/components/button';
```
from `Card.svelte`, storybook crashes.

Pretty much I can't use path aliases in components that have stories.

The error
```
ModuleNotFoundError: Module not found: Error: Can't resolve '$ui/components/button'
```

**Comment by magick93** [comment]
I'm not having this problem.

There are a few `index.ts` files. Maybe check these and see if they need updating.

**Comment by kiranojhanp** [comment]
`import  Button from '$ui/components/button';`
