### ISSUE TITLE
How to get .env values

### ISSUE THREAD

**Issue by magick93** [navneetsharmaui/sveltekit-starter#23]
Hello

I cannot get any on the values from a .env file to work.

For example:
```
console.log(`chucknoris var is ${ environment.apiUrls.CHUCK_NORRIS}`)
```
prints `chucknoris var is undefined`,

I've tried also sorts of variations of `yarn run dev --mode=local --configurations=local`.

And I have both a `.env.local` and .local.env` file.

Any help is appreciated.

**Comment by navneetsharmaui** [comment]
@magick93 the environment file name should start with the .env and if you look through the .env. example and go through the project set you will be able to figure out.
Check the latest code.

**Comment by navneetsharmaui** [comment]
@magick93 You can go through [Vite Documentation](https://vitejs.dev/guide/env-and-mode.html).

**Comment by magick93** [comment]
Thanks @navneetsharmaui
