### ISSUE TITLE
Error with transition fade/blur when page is not reloaded @Home

### ISSUE THREAD

**Issue by dagthomas** [navneetsharmaui/sveltekit-starter#33]
**Describe the bug**
Fade transition with blur only works if you refresh the page @home, and not the other routes.

**To Reproduce**
1. Go to another page than Home and click refresh - 
2. Click on another page than Home (no fade)
3. Click on @Home
4. Fade works again

**Expected behavior**
Expect transition with blur to work no matter what the start page is.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome
 - Version 95.0.4638.69

**Comment by navneetsharmaui** [comment]
@dagthomas The issue is related to how sveltekit itself works. You might notice that if refresh on a page other than home, and go to other page the application whole application will reload until you got to home and come back. I will keep this issue open for now.
