### ISSUE TITLE
Demonstrations of tests

### ISSUE THREAD

**Issue by jtlapp** [navneetsharmaui/sveltekit-starter#37]
I have been unable to get TypeScript tests to work in SvelteKit.

I would love to see demonstrations of tests in this demo.

The README says it includes jest, but it does not.

**Comment by navneetsharmaui** [comment]
@jtlapp You are right about that. I had removed the test setup. The sveltekit is not as stable as we expected it to be right now for tests to be written properly. In addition, the jest setup that I had added initially was not working in all the scenarios, especially with typescript.

**Comment by navneetsharmaui** [comment]
I will keep this issue open for now

**Comment by netham91** [comment]
@navneetsharmaui, what about the sveltekit, storybook and ts combination? Is that stable enough?
