### ISSUE TITLE
Entire Home Page HTML body tag is not showing fully 

### ISSUE THREAD

**Issue by Slyracoon23** [navneetsharmaui/sveltekit-starter#40]
#### Describe the bug

Home page does not show entire HTML body tag.

#### To Reproduce

1. Git clone [sveltekit-starter](https://github.com/navneetsharmaui/sveltekit-starter)
2. yarn install
3. yarn run dev -- --open

#### Expected behavior

By removing the tailwind.css starter class css, flex display.
```
#starter {
	/* display: flex; */
	flex-direction: column;
	min-height: 100%;
	height: 100%;
}
```
The correct layout was achieved
![image](https://user-images.githubusercontent.com/33297016/171067344-a24d20b8-64f0-495b-a6f0-4752f29562c6.png)

#### Screenshots
Current issue
![image](https://user-images.githubusercontent.com/33297016/171067441-84493c5f-1760-4ce2-8782-96b9ccd10619.png)

#### Desktop

Please complete the following information

- OS: Ubuntu 22.04
- Browser Firefox v99.0.1
- Package Manger: Yarn v1.22.18

**Comment by digi4care** [comment]
after or before doesnt matter really do run the "add-css" script

npm run add-css

there are a few css npm scripts available

**Comment by Slyracoon23** [comment]
Cool, thanks.
