### ISSUE TITLE
Upgrade to latest version of svelte

### ISSUE THREAD

**Issue by abeldebruijn** [navneetsharmaui/sveltekit-starter#46]
#### Describe the solution you'd like

Due to the recent changes with svelte mentioned [here](https://www.netlify.com/blog/migrating-breaking-changes-in-sveltekit/), this template needs an update to support the breaking changes. 

Main developer Rich Harris has created a guide to upgrade a repo to the newest stadards: https://github.com/sveltejs/kit/discussions/5774

**Comment by Explosion-Scratch** [comment]
Work in progress on PR #51

**Comment by Explosion-Scratch** [comment]
ok

**Comment by thegausiantheory** [comment]
I am getting this error.. 

PS C:\Users\rezam\codespace\sveltekit-starter> npm run dev

> sveltekit-starter@1.0.0 dev
> npm run check-env && npm run dev:sveltekit

> sveltekit-starter@1.0.0 check-env
> node --loader ts-node/esm scripts/js/check-env.ts

> (node:32140) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
> (Use `node --trace-warnings ...` to show where the warning was created)
> Error [ERR_LOADER_CHAIN_INCOMPLETE]: "ts-node/esm 'resolve'" did not call the next hook in its chain and did not explicitly  signal a short circuit. If this is intentional, include `shortCircuit: true` in the hook's return.
>     at new NodeError (node:internal/errors:400:5)
>     at ESMLoader.resolve (node:internal/modules/esm/loader:850:13)
>     at async ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:7) {
>   code: 'ERR_LOADER_CHAIN_INCOMPLETE'
> }

**Comment by Explosion-Scratch** [comment]
Not sure what's going on, feel free to try with [My PR](https://github.com/navneetsharmaui/sveltekit-starter/pull/51) and suggest any edits you have
