### ISSUE TITLE
tailwind has JIT enabled but doesn't seem to jit anything have to stop and restart to see changes.

### ISSUE THREAD

**Issue by crazedVic** [navneetsharmaui/sveltekit-starter#8]

**Comment by navneetsharmaui** [comment]
@crazedVic The way this project is set up you don't need to restart the server to see the changes for the CSS/tailwind. As the scss is transpiled to CSS, before the dev or production build is initiated, and the generated global css and tailwind css are directly linked in the app.html, the HMR is not supported for them. But the JIT works only in the prod build, not for local. Build the application and check the generated css files.
